USE [NowDb]
GO

/****** Object:  Table [dbo].[LoginAuditTrail] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LoginAuditTrail](
	[AuditId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[DeviceId] [nvarchar](200) NOT NULL,
	[IPAddress] [nvarchar](100) NOT NULL,
	[LoginTime] [DateTime] NOT NULL	 
 CONSTRAINT [PK_LoginAuditTrail] PRIMARY KEY CLUSTERED 
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO